name: Build and Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_TARGET: 54.206.53.213  # main branch deploy target
      SSH_DEV_TARGET: 54.206.53.213  # develop branch deploy target
      NODE_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current branch
        id: branch
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | awk 'BEGIN{FS="/"} {print $3}')"

      - name: Set SSH target based on branch
        run: |
          if [ "${{ steps.branch.outputs.branch }}" == "main" ]; then
            echo "Using main branch SSH target"
            echo "SSH_TARGET=$SSH_TARGET" >> $GITHUB_ENV
          elif [ "${{ steps.branch.outputs.branch }}" == "develop" ]; then
            echo "Using develop branch SSH target"
            echo "SSH_TARGET=$SSH_DEV_TARGET" >> $GITHUB_ENV
          fi

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          if [ "${{ steps.branch.outputs.branch }}" == "main" ]; then
            echo "${{ secrets.SSH_KEY }}" | openssl rsa -out ~/.ssh/id_rsa.pem  # set the SSH key into the ~/.ssh/id_rsa file
          elif [ "${{ steps.branch.outputs.branch }}" == "develop" ]; then
            echo "${{ secrets.SSH_KEY_DEV }}" | openssl rsa -out ~/.ssh/id_rsa.pem  # set the SSH key into the ~/.ssh/id_rsa file
          fi
          chmod 600 ~/.ssh/id_rsa.pem  # set the permissions
          ssh-keyscan "$SSH_TARGET" >> ~/.ssh/known_hosts  # add the host to the known_hosts file
          chmod 644 ~/.ssh/known_hosts  # set the permissions

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin@$SSH_TARGET "cd space/AppFlowy-Website && git fetch && git reset --hard origin/${{ steps.branch.outputs.branch }} && pnpm install && pnpm run build && node run-script.js" || { echo "Failed to execute the command"; exit 1; }
        
