name: Auto Deploy to Development

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-develop:
    runs-on: ubuntu-latest

    env:
      SSH_TARGET: 54.206.53.213
      NODE_ENV: production
      ENVIRONMENT: test


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current branch
        id: branch
        run: echo "::set-output name=branch::$(echo $GITHUB_REF | awk 'BEGIN{FS="/"} {print $3}')"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY_DEV }}" | openssl rsa -out ~/.ssh/id_rsa.pem  # set the SSH key into the ~/.ssh/id_rsa file
          chmod 600 ~/.ssh/id_rsa.pem  # set the permissions
          ssh-keyscan "$SSH_TARGET" >> ~/.ssh/known_hosts  # add the host to the known_hosts file
          chmod 644 ~/.ssh/known_hosts  # set the permissions

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pem admin@$SSH_TARGET "cd space/AppFlowy-Website && git fetch && git reset --hard origin/${{ steps.branch.outputs.branch }} && pnpm run deploy:prod" || { echo "Failed to execute the command"; exit 1; }
        
