name: Test
on: [ pull_request ]

env:
  NODE_VERSION: "20.12.0"
  PNPM_VERSION: "8.5.0"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          npm install -g pnpm@${{ env.PNPM_VERSION }}
          pnpm install
      - name: Build
        run: |
          NODE_ENV=test pnpm run build
      - name: Run lint
        run: |
          pnpm run lint
      - name: Run tests
        run: |
          NODE_ENV=test pnpm run start &
          pnpm run test:headless

